stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/customerdata.csv
    outs:
    - data/raw/customerdata.csv
  

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/split_data.py
    - data/raw/customerdata.csv
    outs:
    - data/processed/train_customerdata.csv
    - data/processed/test_customerdata.csv

  train_and_evaluate:
    cmd: python src/train_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_customerdata.csv
    - data/processed/test_customerdata.csv 
    - src/train_evaluate.py
    params:
    - estimators.RandomForestClassifier.params.n_estimators
    - estimators.RandomForestClassifier.params.min_samples_split
    - estimators.RandomForestClassifier.params.min_samples_leaf
    - estimators.RandomForestClassifier.params.max_features
    - estimators.RandomForestClassifier.params.max_depth
    - estimators.RandomForestClassifier.params.criterion
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib