base:
  project: churnapp-project
  random_state: 42
  target_col: Churn

data_source:
  sql_source: data_given/customerdata.csv

load_data:
  raw_dataset_csv: data/raw/customerdata.csv

split_data:
  train_path: data/processed/train_customerdata.csv
  test_path: data/processed/test_customerdata.csv
  test_size: 0.2

estimators:
  RandomForestClassifier:
    params:
      n_estimators: 2000
      min_samples_split: 12
      min_samples_leaf: 6
      max_features: 'sqrt'
      max_depth: 1000
      criterion: 'gini'

model_dir: saved_models

testing_path:
  json_file_path: ML-WorkFlow/tests

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib